services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRESQL_DATABASE}'
      - 'POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRESQL_USERNAME}'
    ports:
      - '5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
