services:

  postgres:
    image: 'postgres:17.4-bullseye'
    environment:
      - 'POSTGRES_DB=${POSTGRESQL_DATABASE}'
      - 'POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRESQL_USERNAME}'
    ports:
      - '${POSTGRESQL_PORT}:5432'

  rabbitmq:
    image: 'rabbitmq:4.1-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}'
      - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}'
    ports:
      - '${RABBITMQ_PORT}:5672'

  pgadmin:
    image: 'dpage/pgadmin4:9.2'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=${PGADMIN_USERNAME}'
      - 'PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}'
    ports:
      - '${PGADMIN_PORT}:80'
    depends_on:
      - postgres
