spring:
  application:
    name: Generic Microservice Accounts
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_accounts
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: America/Sao_Paulo
